[package]
name = "gpt6register"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.11"
tokio = { version = "1.20.1", features = ["full"] }
serde = "1.0.143"
serde_json = "1.0.83"