[package]
name = "code3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#rand = "0.8.5"
rand = "^0.8.3"
#rand = { git = "https://github.com/rust-random/rand.git", branch = "master" }